config/routes.rb
Ebulletin::Application.routes.draw do
  

  resources :publics

  resources :events

  devise_for :users
	
	get "user/index"
	match "user/approve" => 'user#approve'
  get "preview/download"
	get "preview/generate"
  get "preview/raw"
	match 'preview' => 'preview#index'
	match 'stories/sort' => 'stories#sort'
	match 'jobs/sort' => 'jobs#sort'
	match 'jobs/delete_all' => 'jobs#delete_all'
  match 'publics/sort' => 'publics#sort'
	
  resources :jobs
  resources :stories

  root :to => 'preview#index'

end

app/models/public.rb
class Public < ActiveRecord::Base
  attr_accessible :body, :position, :title
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  # GET /publics
  # GET /publics.json
  def index
    @publics = Public.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @publics }
    end
  end

  # GET /publics/1
  # GET /publics/1.json
  def show
    @public = Public.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @public }
    end
  end

  # GET /publics/new
  # GET /publics/new.json
  def new
    @public = Public.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @public }
    end
  end

  # GET /publics/1/edit
  def edit
    @public = Public.find(params[:id])
  end

  # POST /publics
  # POST /publics.json
  def create
    @public = Public.new(params[:public])

    respond_to do |format|
      if @public.save
        format.html { redirect_to preview_url, notice: 'Public was successfully created.' }
        format.json { render json: @public, status: :created, location: @public }
      else
        format.html { render action: "new" }
        format.json { render json: @public.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /publics/1
  # PUT /publics/1.json
  def update
    @public = Public.find(params[:id])

    respond_to do |format|
      if @public.update_attributes(params[:public])
        format.html { redirect_to preview_url, notice: 'Public was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @public.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publics/1
  # DELETE /publics/1.json
  def destroy
    @public = Public.find(params[:id])
    @public.destroy

    respond_to do |format|
      format.html { redirect_to preview_url }
      format.json { head :no_content }
    end
  end

  def sort    
    public_ids = params["publics"]
    counter = 1
    public_ids.each do |id|
      current_public = Public.find(id)
      current_public.position = counter
      current_public.save
      counter +=1
    end
    render :nothing => true
  end
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/views/publics/_form.html.erb
<div class="row">
  <div class="large-8 columns large-centered">

    <%= form_for(@public) do |f| %>
      <% if @public.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@public.errors.count, "error") %> prohibited this public from being saved:</h2>

          <ul>
          <% @public.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>


        <%= f.label :title %>
        <%= f.text_field :title %>

        <%= f.label :body %>
        <%= f.text_area :body %><br>

        <%= f.label :position %>
        <%= f.number_field :position %>

        <%= f.submit :class => "small button success radius" %>
        <%= link_to 'Back', preview_url %>
    <% end %>
  </div>
</div>

app/views/publics/edit.html.erb
<div class="row">
	<div class="large-8 columns large-centered">
		<h1>Edit Public Interest News</h1>
	</div>
</div>

<%= render 'form' %>

app/views/publics/index.html.erb
<h1>Listing publics</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Position</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @publics.each do |public| %>
  <tr>
    <td><%= public.title %></td>
    <td><%= public.body %></td>
    <td><%= public.position %></td>
    <td><%= link_to 'Show', public %></td>
    <td><%= link_to 'Edit', edit_public_path(public) %></td>
    <td><%= link_to 'Destroy', public, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Public', new_public_path %>

app/views/publics/new.html.erb
<div class="row">
	<div class="large-8 columns large-centered">
		<h1>New Public Interest News</h1>
	</div>
</div>

<%= render 'form' %>

app/views/publics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @public.title %>
</p>

<p>
  <b>Body:</b>
  <%= @public.body %>
</p>

<p>
  <b>Position:</b>
  <%= @public.position %>
</p>


<%= link_to 'Edit', edit_public_path(@public) %> |
<%= link_to 'Back', publics_path %>