config/routes.rb
Ebulletin::Application.routes.draw do
  

  resources :publics

  resources :events

  devise_for :users
	
	get "user/index"
	match "user/approve" => 'user#approve'
  get "preview/download"
	get "preview/generate"
  get "preview/raw"
	match 'preview' => 'preview#index'
	match 'stories/sort' => 'stories#sort'
	match 'jobs/sort' => 'jobs#sort'
	match 'jobs/delete_all' => 'jobs#delete_all'
  match 'publics/sort' => 'publics#sort'
	
  resources :jobs
  resources :stories

  root :to => 'preview#index'

end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessible :archived, :body, :call_to_action, :image_name, :link, :position, :title
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/new
  # GET /stories/new.json
  def new
    @story = Story.new
		
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(params[:story])

    respond_to do |format|
      if @story.save
        format.html { redirect_to preview_url, notice: 'Story was successfully created.' }
        format.json { render json: @story, status: :created, location: @story }
      else
        format.html { render action: "new" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    @story = Story.find(params[:id])

    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { redirect_to preview_url, notice: 'Story was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to preview_url }
      format.json { head :no_content }
    end
  end
	
	def sort		
			story_ids = params["stories"]
			counter = 1
			story_ids.each do |id|
				current_story = Story.find(id)
				current_story.position = counter
				current_story.save
				counter += 1
			end
			render :nothing => true
	end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<div class="row">
	<div class="large-8 columns large-centered">
	<%= form_for(@story) do |f| %>
		<% if @story.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

				<ul>
				<% @story.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
				</ul>
			</div>
		<% end %>

	<%= f.label :title %>
    <%= f.text_field :title %>
    
	<%= f.label :body %>
    <%= f.text_area :body %>
    <br />
	<%= f.label :image_name %>
    <%= f.text_field :image_name %>
	
    <%= f.label :call_to_action %>
    <%= f.text_field :call_to_action %>
		
    <%= f.label :link %>
    <%= f.text_field :link %>

    <%= f.submit :class => "small button success radius" %>
	<%= link_to "Preview", "#", {:class => "small button info radius", 'data-reveal-id' => "preview_story_modal"} %>
	<%= link_to 'Back', preview_url %>
		</div>
		<!-- Warning.  There be dragons down in this code.  There is lots of inline css and other horrible things. -->
		<div id="preview_story_modal" class="reveal-modal">
			<a class="close-reveal-modal">&#215;</a>
			<table class="content" align="center" cellspacing="0" cellpadding="0" style="background-color: #fff; width: 600px;" bgcolor="#fff">
				<tr>
					<td class="content-title" style="cursor: auto; vertical-align: top; margin: 0; padding: 0; border: none;" valign="top">
						<h2 id="preview_story_title" style="font-family: Georgia, serif; font-weight: 500; color: #fff; text-shadow: 0 1px black; font-size: 28px; line-height: 40px; font-variant: small-caps; background-color: #98012e; margin: 0; border: 10px solid #fff; cursor: auto;">&nbsp;</h2>
					</td>
				</tr>
				<tr>
					<td class="content-body" style="vertical-align: top; margin: 0; padding: 0; border: 10px solid #fff;" valign="top">
						<!-- TABLE FOR THE MAIN IMAGE TO FLOAT RIGHT -->
						<table class="main-image" align="right" cellpadding="0" cellspacing="0">
							<tbody>
								<tr>
									<td>
										<img class="pic" width="270" id="preview_image" src=""><img class="shadow" src="/assets/content-img-shadow-7c071f9af7c427600201ba3868809f8f.png">
									</td>
								</tr>
							</tbody>
						</table>
						<!-- CONTENT TEXT GOES HERE -->
						<p id="preview_story_body"></p><br />	
						<a style="font-family: Helvetica, Arial, sans-serif; font-size: 16px; line-height: 22px; letter-spacing: .2px; color: #98012e; font-weight: 400; text-decoration: underline; margin: 0;" id="preview_story_call_to_action" href="#"></a>
					</td>
				</tr>
			</table>
		</div>
	</div>
<% end %>

app/views/stories/edit.html.erb
<div class="row">
	<div class="large-8 columns large-centered">
		<h1>Editing story</h1>
	</div>
</div>
<%= render 'form' %>

app/views/stories/index.html.erb
<h1>Listing stories</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Image name</th>
    <th>Position</th>
    <th>Archived</th>
    <th>Call to action</th>
    <th>Link</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stories.each do |story| %>
  <tr>
    <td><%= story.title %></td>
    <td><%= story.body %></td>
    <td><%= story.image_name %></td>
    <td><%= story.position %></td>
    <td><%= story.archived %></td>
    <td><%= story.call_to_action %></td>
    <td><%= story.link %></td>
    <td><%= link_to 'Show', story %></td>
    <td><%= link_to 'Edit', edit_story_path(story) %></td>
    <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<div class="row">
	<div class="large-8 columns large-centered">
		<h1>New story</h1>
	</div>
</div>
<%= render 'form' %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @story.title %>
</p>

<p>
  <b>Body:</b>
  <%= @story.body %>
</p>

<p>
  <b>Image name:</b>
  <%= @story.image_name %>
</p>

<p>
  <b>Position:</b>
  <%= @story.position %>
</p>

<p>
  <b>Archived:</b>
  <%= @story.archived %>
</p>

<p>
  <b>Call to action:</b>
  <%= @story.call_to_action %>
</p>

<p>
  <b>Link:</b>
  <%= @story.link %>
</p>


<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', preview_url %>